
name: Hugo
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  hugo:
    name: Hugo
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          path: master
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages
      - name: Install dependencies
        run: |
          sudo apt update || true
          sudo apt --yes --no-install-recommends install hugo
      - name: Generate docs
        run: |
          cd master
          hugo
      - name: Copy docs
        run: |
          rsync --archive --human-readable --verbose --delete --exclude=.git master/public/. pages
      - name: Commit docs
        run: |
          cd pages
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all .
          git commit --amend --reset-author --message='Hugo docs for ${{ github.sha }}'
          git push --force
